---
# playbook.yaml
- name: "Create Approle Wrapped Secret ID"
  hosts: tag_vault_agent_true
  gather_facts: true

  tasks:
    - debug: msg="{{ lookup('env','VAULT_SECRET_ID') }} is the secret id."
    - debug: msg="{{ ansible_facts['nodename'] }}"
    - name: Create approle secret-id
      local_action:
        module: hashivault_approle_role_secret
        state: present
        verify: false
        authtype: approle
        secret_id: "{{ lookup('env','VAULT_SECRET_ID') }}"
        name: "{{ ansible_facts['nodename'] }}"
        wrap_ttl: 5m
      register: vault_approle_role_secret_create

    - name: Write wrapped token to remote host
      lineinfile:
        state: present
        create: true
        line: "{{vault_approle_role_secret_create.wrap_info.token}}"
        path: /etc/vault.d/secretid
      become: true
      become_method: sudo

    - name: Start Vault
      systemd:
        name: vault
        enabled: yes
        state: started